[package]
org = "thath"
name = "ProjectBallerina"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true


[dependencies]
mysql = { version = "1.3.2", repository = "central" }